export {
  BOUND_FEEDBACK_MODES,
  DEFAULT_CALLIGRAPH_SETTINGS,
  DEFAULT_FORMAT_SETTINGS,
  DEFAULT_INPUT_SETTINGS,
  DEFAULT_LOGO_SETTINGS,
  DEFAULT_SCRUB_FIELD_SETTINGS,
  DEFAULT_SCRUB_SETTINGS,
  LOGO_ICON_OPTIONS,
  ScrubLogoIcon,
  ScrubNumberField,
  ScrubNumberInput,
  getScrubCursorClass,
  normalizeScrubFieldSettings,
  useNumberScrub,
  type BoundFeedbackMode,
  type BoundFeedbackSource,
  type BoundFeedbackState,
  type CalligraphSettings,
  type FormatSettings,
  type InputSettings,
  type LogoSettings,
  type ScrubFieldSettings,
  type ScrubNumberFieldProps,
  type ScrubSettings,
  type ScrubState,
} from "../../../components/ui/scrub-number-input"

export {
  clampNumber,
  countDraftDecimalPlaces,
  formatDisplayValue,
  formatMinimalDisplayValue,
  getAtBound,
  getBoundEdge,
  getDecimalPlaces,
  getCoarseModifierLabel,
  getFineModifierLabel,
  getScrubPointerDelta,
  hasExceededScrubThreshold,
  isCoarseModifierPressed,
  isFineModifierPressed,
  isMacPlatform,
  isModifierKeyPressed,
  applyStepDelta,
  normalizeFiniteNumber,
  normalizeNumberFieldBounds,
  normalizePositiveFiniteStep,
  normalizeScrubThreshold,
  normalizeWheelSensitivity,
  preserveDisplayDraft,
  resolveDisplayDecimalPlaces,
  quantizeNumber,
  resolveActiveStep,
  resolveCoarseModifierKey,
  resolveFineModifierKey,
  resolveFineStep,
  resolveQuantizeStep,
  resolveScrubStepModifiers,
  sanitizeNumericDraft,
  toModifierKeys,
  getValueDecimalPlaces,
  stepFromDecimalPlaces,
  boundOverflow,
  type CoarseModifier,
  type DisplayFormat,
  type FineModifier,
  type ModifierKey,
} from "../../../lib/scrub-number-math"
